name: cloning another repository

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  all: 
    name: cloning another repository
    runs-on: ubuntu-latest
    steps: 
      - name: clone repo
        uses: actions/checkout@v2
        with: 
          repository: 'cr0wg4n/my-path' # private, still works if is your repository 
          # repository: 'cr0wg4n/plantilla-latex-proyecto-de-grado' # public, don't need a token
          token: ${{ secrets.GH_ACCESS_TOKEN }} # only if your cloned repo is private
      - name: get evidences
        run: ls -la