name: testing mongo (docker-compose method)

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  all: 
    name: testing mongo 
    runs-on: ubuntu-latest
    steps:
      - name: clone actual repository
        uses: actions/checkout@v2

      - name: run docker compose
        run: docker-compose -f ".docker/docker-compose.mongo.yml" up -d

      - name: sleep 
        run: docker ps
        
      - name: mongo is up?
        run: export $(cat .env | xargs) && nc -zvv localhost $MONGO_PORT

