name: testing mongo (docker-compose method)

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  all: 
    name: testing mongo 
    runs-on: ubuntu-latest
    steps:
      - name: clone actual repository
        uses: actions/checkout@v2
        with:
          path: actual

      - name: go to actual context
        run: cd actual && ls -a

      - name: run docker compose
        run: cd .docker && docker-compose -f docker-compose.mongo.yml up -d && sleep 5 && cd ..
        
      - name: mongo is up?
        run: nc -zvv localhost $MONGO_PORT

      - name: load environment file
        run: source .env

      - name: test env loading
        run: echo $MONGO_PORT
